
package aplikasilaundry.view.dialog;
import aplikasilaundry.controller.TransaksiController;
//Mengimpor FrameDashboard
import aplikasilaundry.view.frame.FrameDashboard;

//Mengimpor SwingUtilities
import javax.swing.SwingUtilities;
//Mengimpor controller pengguna
import aplikasilaundry.controller.PenggunaController;

//Mengimpor panel Pengaturan
import aplikasilaundry.view.panel.Pengaturan;

import aplikasilaundry.controller.LayananController;
import aplikasilaundry.model.Layanan;
public class popUpKonfirmasiHapus extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(popUpKonfirmasiHapus.class.getName());
//Controller transaksi
private TransaksiController controllerTransaksi;
//Controller pengguna
private PenggunaController controllerPengguna;

//ID pengguna yang akan dihapus
private int idPengguna;

//Panel Pengaturan
private Pengaturan pengaturan;

//Nomor nota yang akan dihapus
private String noNota;

//Popup edit yang membuka dialog ini
private popUpPensilEdit popupEdit;

//Controller layanan
private LayananController controllerLayanan;

//Menyimpan data layanan
private Layanan layanan;

//Menyimpan panel Pengaturan
private Pengaturan panel;
    
  //Constructor popup konfirmasi hapus
public popUpKonfirmasiHapus(
        java.awt.Frame parent,
        boolean modal,
        Pengaturan panel,
        Layanan layanan) {

    super(parent, modal);

    initComponents();

    //Membuat controller
   controllerLayanan =
        new LayananController();

    //Menyimpan panel
    this.panel = panel;

    //Menyimpan layanan
    this.layanan = layanan;

}
//Constructor pengguna
public popUpKonfirmasiHapus(
        java.awt.Frame parent,
        boolean modal,
        int idPengguna,
        Pengaturan pengaturan){

    super(parent, modal);

    initComponents();

    controllerPengguna =
            new PenggunaController();

    this.idPengguna = idPengguna;
    this.pengaturan = pengaturan;

}
//Constructor transaksi
public popUpKonfirmasiHapus(
        java.awt.Frame parent,
        boolean modal,
        String noNota,
        popUpPensilEdit popupEdit) {

    super(parent, modal);

    initComponents();

    //Membuat controller transaksi
    controllerTransaksi =
            new TransaksiController();

    //Menyimpan nomor nota
    this.noNota = noNota;

    //Menyimpan popup edit
    this.popupEdit = popupEdit;

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Container (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Konfirmasi Hapus");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(153, 153, 153));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Apakah Anda yakin ingin menghapus data ini?");

        btnBatal.setForeground(new java.awt.Color(102, 102, 102));
        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.setPreferredSize(new java.awt.Dimension(140, 43));
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnHapus.setBackground(new java.awt.Color(251, 44, 54));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setPreferredSize(new java.awt.Dimension(140, 43));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
       //Jika menghapus transaksi
    if(noNota != null){

        //Menghapus transaksi
        controllerTransaksi.hapusTransaksi(noNota);

        //Mengambil FrameDashboard
        FrameDashboard frame =
                (FrameDashboard)
                SwingUtilities.getWindowAncestor(popupEdit);

        //Refresh seluruh panel
        frame.getDataLaundry().refreshSemuaPanel();

        //Menutup popup edit
        popupEdit.dispose();

    }
    //Jika menghapus pengguna
    else if(idPengguna != 0){

        //Menghapus pengguna
        controllerPengguna.hapus(idPengguna);

        //Refresh tabel pengguna
        if(pengaturan != null){
            pengaturan.tampilPengguna();
        }
    }
        //Jika menghapus layanan
else if(layanan != null){

    //Menghapus layanan
    controllerLayanan.hapus(
            layanan.getIdLayanan());

    //Refresh tabel layanan
    if(panel != null){
        panel.tampilLayanan();
    }



    }

    //Menutup popup konfirmasi
    dispose();


    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
