/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package aplikasilaundry.view.dialog;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
//Mengimpor controller pengaturan
import aplikasilaundry.controller.PengaturanStrukController;

//Mengimpor model pengaturan
import aplikasilaundry.model.PengaturanStruk;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
public class popUpCetakStruk extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(popUpCetakStruk.class.getName());
 //Controller pengaturan
private PengaturanStrukController controllerPengaturan;
//Menyimpan slogan atau keterangan laundry
private String keterangan;
//Data pengaturan
private PengaturanStruk pengaturan;
//Model tabel detail struk
private DefaultTableModel model;
    /**
     * Creates new form popUpCetakStruk
     */
    //Constructor popup cetak struk
public popUpCetakStruk(java.awt.Frame parent,
                       boolean modal) {

    super(parent, modal);

    initComponents();
  
    tblDetailStruk.setSize(printStruk.getPreferredSize());

    printStruk.doLayout();
    printStruk.validate();

    StyledDocument doc = tFooter.getStyledDocument();

    SimpleAttributeSet center = new SimpleAttributeSet();
    StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);

    doc.setParagraphAttributes(0, doc.getLength(), center, false);

//Membuat controller pengaturan
controllerPengaturan =
        new PengaturanStrukController();

//Menampilkan informasi laundry
tampilPengaturan();
    //Mengambil model tabel
model =
        (DefaultTableModel)
        tblDetailStruk.getModel();

   

//Menampilkan detail transaksi
//tampilDetail();

}
//Mengambil slogan laundry
public String getKeterangan() {
    return keterangan;
}

//Mengubah slogan laundry
public void setKeterangan(String keterangan) {
    this.keterangan = keterangan;
}
//Method menampilkan informasi pengaturan struk
private void tampilPengaturan(){

    //Mengambil data pengaturan dari database
    pengaturan = controllerPengaturan.getPengaturan();

    //Jika data ditemukan
    if(pengaturan != null){

        //Menampilkan nama bisnis
        lblNamaBisnis.setText(
                pengaturan.getNamaBisnis());

        //Menampilkan alamat laundry
        lblAlamatLaundry.setText(
                pengaturan.getAlamat());

        //Menampilkan nomor HP laundry
        lblNoHpLaundry.setText(
                pengaturan.getNoHp());

        //Menampilkan footer struk
        tFooter.setText(
                pengaturan.getFooterStruk());

    }

}
//Method menerima data preview struk
public void setPreviewData(

        String nama,
        String noHp,
        String alamat,
        String totalBerat,
        String totalBiji,
        String totalHarga,
        javax.swing.JTable tabel){

    //Menampilkan data pelanggan
    lblPelanggan.setText(nama);
    lblNoHp.setText(noHp);
    lblAsal.setText(alamat);

    //Menampilkan ringkasan
    lblTotalBerat.setText(totalBerat);
    lblTotalBiji.setText(totalBiji);
    lblTotalHarga.setText(totalHarga);

    //Mengambil model tabel popup
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
            tblDetailStruk.getModel();

    model.setRowCount(0);

    //Mengambil model tabel konfirmasi
    javax.swing.table.DefaultTableModel asal =
            (javax.swing.table.DefaultTableModel)
            tabel.getModel();

    //Menyalin seluruh baris
    for(int i = 0; i < asal.getRowCount(); i++){

        Object[] row = new Object[asal.getColumnCount()];

        for(int j = 0; j < asal.getColumnCount(); j++){

            row[j] = asal.getValueAt(i, j);

        }

        model.addRow(row);

    }

}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printStruk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblNamaBisnis = new javax.swing.JLabel();
        lblAlamatLaundry = new javax.swing.JLabel();
        lblNoHpLaundry = new javax.swing.JLabel();
        lblKeterangan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNoNota = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblJamMasuk = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblPelanggan = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblNoHp = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblAsal = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        lblTotalBerat = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        lblTotalBiji = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        lblTotalHarga = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        tFooter = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        tblDetailStruk = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        printStruk.setBackground(new java.awt.Color(239, 238, 245));
        printStruk.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 226, 230), 2)));
        printStruk.setPreferredSize(new java.awt.Dimension(321, 500));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/logo 1.png"))); // NOI18N

        lblNamaBisnis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamaBisnis.setText("MOJOSARI LAUNDRY");

        lblAlamatLaundry.setText("Bersih, Suci, Wangi");

        lblNoHpLaundry.setText("Bersih, Suci, Wangi");

        lblKeterangan.setText("Bersih, Suci, Wangi");

        jPanel4.setBackground(new java.awt.Color(239, 238, 245));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16));
        jPanel1.setPreferredSize(new java.awt.Dimension(304, 130));
        jPanel1.setLayout(new java.awt.GridLayout(6, 0, 8, 5));

        jPanel5.setBackground(new java.awt.Color(239, 238, 245));
        jPanel5.setLayout(new java.awt.BorderLayout(13, 0));

        lblNoNota.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblNoNota.setText("INV-260508-001");
        jPanel5.add(lblNoNota, java.awt.BorderLayout.CENTER);

        jPanel17.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel32.setText("No Nota");
        jPanel17.add(jLabel32, java.awt.BorderLayout.LINE_START);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText(":");
        jLabel33.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel17.add(jLabel33, java.awt.BorderLayout.LINE_END);

        jPanel5.add(jPanel17, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel5);

        jPanel9.setBackground(new java.awt.Color(239, 238, 245));
        jPanel9.setLayout(new java.awt.BorderLayout(13, 0));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTanggal.setText("08/05/2026");
        jPanel9.add(lblTanggal, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel30.setText("Tanggal");
        jPanel16.add(jLabel30, java.awt.BorderLayout.LINE_START);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText(":");
        jLabel31.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel16.add(jLabel31, java.awt.BorderLayout.LINE_END);

        jPanel9.add(jPanel16, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(239, 238, 245));
        jPanel10.setLayout(new java.awt.BorderLayout(13, 0));

        lblJamMasuk.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblJamMasuk.setText("10:30:45");
        jPanel10.add(lblJamMasuk, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel24.setText("Jam Masuk");
        jPanel8.add(jLabel24, java.awt.BorderLayout.LINE_START);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText(":");
        jLabel25.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel8.add(jLabel25, java.awt.BorderLayout.LINE_END);

        jPanel10.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(239, 238, 245));
        jPanel11.setLayout(new java.awt.BorderLayout(13, 0));

        lblPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPelanggan.setText("Siti Aisyah");
        jPanel11.add(lblPelanggan, java.awt.BorderLayout.CENTER);

        jPanel14.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel26.setText("Pelanggan");
        jPanel14.add(jLabel26, java.awt.BorderLayout.LINE_START);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText(":");
        jLabel27.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel14.add(jLabel27, java.awt.BorderLayout.LINE_END);

        jPanel11.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(239, 238, 245));
        jPanel12.setLayout(new java.awt.BorderLayout(13, 0));

        lblNoHp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblNoHp.setText("0857-9155-9991");
        jPanel12.add(lblNoHp, java.awt.BorderLayout.CENTER);

        jPanel15.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel28.setText("No HP");
        jPanel15.add(jLabel28, java.awt.BorderLayout.LINE_START);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText(":");
        jLabel29.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel15.add(jLabel29, java.awt.BorderLayout.LINE_END);

        jPanel12.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(239, 238, 245));
        jPanel13.setLayout(new java.awt.BorderLayout(13, 0));

        lblAsal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAsal.setText("PPP.KH.A.BASTHOMI");
        jPanel13.add(lblAsal, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel34.setText("Asal");
        jPanel18.add(jLabel34, java.awt.BorderLayout.LINE_START);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText(":");
        jLabel35.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel18.add(jLabel35, java.awt.BorderLayout.LINE_END);

        jPanel13.add(jPanel18, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel13);

        jPanel19.setBackground(new java.awt.Color(239, 238, 245));
        jPanel19.setFocusTraversalPolicyProvider(true);

        jPanel20.setBackground(new java.awt.Color(239, 238, 245));

        lblTotalBerat.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTotalBerat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBerat.setText("2.0 Kg");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel44.setText("TOTAL BERAT");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotalBerat)
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(239, 238, 245));

        lblTotalBiji.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTotalBiji.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBiji.setText("1 Biji");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel46.setText("TOTAL BIJI");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalBiji, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotalBiji)
                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(239, 238, 245));

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalHarga.setText("Rp 18.000");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel48.setText("TOTAL HARGA");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotalHarga)
                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("------------------------------------------------------");
        jLabel49.setPreferredSize(new java.awt.Dimension(304, 16));

        jPanel23.setBackground(new java.awt.Color(239, 238, 245));
        jPanel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16));
        jPanel23.setPreferredSize(new java.awt.Dimension(304, 84));

        tFooter.setBackground(new java.awt.Color(239, 238, 245));
        tFooter.setBorder(null);
        tFooter.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tFooter.setEnabled(false);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16));
        jPanel6.setPreferredSize(new java.awt.Dimension(304, 124));
        jPanel6.setLayout(new java.awt.CardLayout());

        tblDetailStruk.setBackground(new java.awt.Color(239, 238, 245));
        tblDetailStruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPanel6.add(tblDetailStruk, "card3");

        jLabel20.setBackground(new java.awt.Color(239, 238, 245));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("------------------------------------------------------");
        jLabel20.setPreferredSize(new java.awt.Dimension(304, 16));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(112, 112, 112))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout printStrukLayout = new javax.swing.GroupLayout(printStruk);
        printStruk.setLayout(printStrukLayout);
        printStrukLayout.setHorizontalGroup(
            printStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printStrukLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(printStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAlamatLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNamaBisnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNoHpLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(printStrukLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        printStrukLayout.setVerticalGroup(
            printStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printStrukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(printStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printStrukLayout.createSequentialGroup()
                        .addComponent(lblNamaBisnis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlamatLaundry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNoHpLaundry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKeterangan))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCetak.setBackground(new java.awt.Color(37, 99, 235));
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Container (2).png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        btnTutup.setText("Tutup");
        btnTutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutup.addActionListener(this::btnTutupActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(printStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {

        // Mengambil printer yang tersedia
        PrinterJob job = PrinterJob.getPrinterJob();

        // Mengambil pengaturan halaman bawaan
        PageFormat format = job.defaultPage();

        // Membuat objek kertas
        Paper paper = new Paper();

        // Lebar kertas 80 mm (dalam satuan point)
        double width = 164.41;

        // Tinggi kertas mengikuti tinggi panel struk
        double height = printStruk.getPreferredSize().height * 72.0 / 96.0;

        // Mengatur ukuran kertas
        paper.setSize(width, height);

        // Seluruh area kertas dapat digunakan untuk mencetak
        paper.setImageableArea(0, 0, width, height);

        // Menggunakan ukuran kertas yang telah dibuat
        format.setPaper(paper);

        // Menentukan isi yang akan dicetak
        job.setPrintable((graphics, pageFormat, pageIndex) -> {

            // Printer hanya mencetak satu halaman
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            // Mengubah Graphics menjadi Graphics2D
            Graphics2D g2 = (Graphics2D) graphics;

            // Memindahkan titik awal cetak ke area yang dapat dicetak
            g2.translate(
                    pageFormat.getImageableX(),
                    pageFormat.getImageableY()
            );

            // Memastikan layout panel sudah diperbarui
            printStruk.doLayout();

            // Menghitung skala agar lebar panel sesuai dengan lebar kertas
            double scale = pageFormat.getImageableWidth()
                    / printStruk.getPreferredSize().width;

            // Menerapkan skala
            g2.scale(scale, scale);

            // Mencetak isi panel struk
            printStruk.printAll(g2);

            // Mengembalikan status bahwa halaman tersedia
            return Printable.PAGE_EXISTS;

        }, format);

        // Menampilkan dialog pemilihan printer
        if (job.printDialog()) {

            // Mulai proses mencetak
            job.print();

            // Menutup form setelah selesai mencetak
            dispose();

        }

    } catch (PrinterException e) {

        // Menampilkan pesan jika terjadi kesalahan saat mencetak
        JOptionPane.showMessageDialog(
                this,
                "Gagal mencetak struk!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    }
                                             

  

    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
         //Menutup popup cetak struk
    dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                popUpCetakStruk dialog = new popUpCetakStruk(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAlamatLaundry;
    private javax.swing.JLabel lblAsal;
    private javax.swing.JLabel lblJamMasuk;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblNamaBisnis;
    private javax.swing.JLabel lblNoHp;
    private javax.swing.JLabel lblNoHpLaundry;
    private javax.swing.JLabel lblNoNota;
    private javax.swing.JLabel lblPelanggan;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotalBerat;
    private javax.swing.JLabel lblTotalBiji;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JPanel printStruk;
    private javax.swing.JTextPane tFooter;
    private javax.swing.JTable tblDetailStruk;
    // End of variables declaration//GEN-END:variables
}
