package aplikasilaundry.view.panel;

import aplikasilaundry.controller.TransaksiController;
import aplikasilaundry.model.Transaksi;
import aplikasilaundry.util.TableStyle;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Diproses extends javax.swing.JPanel {

    private TransaksiController controller;

    public Diproses() {
        initComponents();

        //Membuat objek controller
        controller = new TransaksiController();

        //Menampilkan data
        tampilData();
        tblProses.getColumnModel()
                .getColumn(5);
        TableStyle.TableStyle(tblProses);
    }

    private void tampilData() {

        DefaultTableModel model
                = (DefaultTableModel) tblProses.getModel();

        model.setRowCount(0);

        List<Transaksi> list = controller.getDiproses();

        for (Transaksi t : list) {

            //Menyimpan teks jenis layanan
            String jenis = t.getJenis();

            //Jika jumlah item lebih dari satu
            if (t.getJumlahItem() > 1) {

                //Menambahkan jumlah item lainnya
                jenis = jenis + " +" + (t.getJumlahItem() - 1);

            }

            //Menambahkan data ke tabel
            model.addRow(new Object[]{
                //Nomor nota
                t.getNoNota(),
                //Nama pelanggan
                t.getNamaPelanggan(),
                //Jam masuk
                t.getJamMasuk(),
                //Jenis layanan
                jenis,
                //Total harga
                t.getTotalHarga(),
                //Status transaksi
                t.getStatus()

            });
        }

    }
    
    //Method untuk memperbarui data tabel
    public void refreshData() {

        //Menampilkan ulang seluruh data transaksi
        tampilData();

    }
    
    //Method untuk mengambil JTable Diproses
    public javax.swing.JTable getTblDiproses() {

        //Mengembalikan tabel Diproses
        return tblProses;

    }
    
    //Method untuk mengambil JTable Laundry Masuk
    public javax.swing.JTable getTblMasuk() {

        //Mengembalikan tabel Laundry Masuk
        return tblProses;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProses = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(240, 243, 247));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMinimumSize(new java.awt.Dimension(1006, 75));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        jPanel17.setLayout(new java.awt.CardLayout());

        tblProses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblProses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Nota", "Nama Pelanggan", "Jam Masuk", "Jenis", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProses.setGridColor(new java.awt.Color(240, 243, 247));
        tblProses.setRowHeight(35);
        tblProses.setSelectionBackground(new java.awt.Color(195, 220, 255));
        tblProses.setShowGrid(true);
        jScrollPane1.setViewportView(tblProses);

        jPanel17.add(jScrollPane1, "card2");

        jPanel2.add(jPanel17, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProses;
    // End of variables declaration//GEN-END:variables
}
