package aplikasilaundry.view.panel;

//Mengimpor controller transaksi
import aplikasilaundry.controller.TransaksiController;

//Mengimpor model transaksi
import aplikasilaundry.model.Transaksi;
import aplikasilaundry.util.FormatJam;

//Mengimpor DefaultTableModel
import javax.swing.table.DefaultTableModel;

//Mengimpor collection
import java.util.List;
import aplikasilaundry.util.FormatRupiah;
import aplikasilaundry.util.TableStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class LaundryMasuk extends javax.swing.JPanel {
//Menyimpan controller transaksi

    private TransaksiController controller;

    public LaundryMasuk() {
        initComponents();
        //Membuat objek controller
        controller = new TransaksiController();
        TableStyle.TableStyle(tblMasuk);
        
        // ================= Alignment Tabel =================

        // Renderer tengah
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        // Renderer kiri
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        left.setHorizontalAlignment(SwingConstants.LEFT);

        // No Nota
        tblMasuk.getColumnModel().getColumn(0).setCellRenderer(left);

        // Nama Pelanggan
        tblMasuk.getColumnModel().getColumn(1).setCellRenderer(left);

        // Jam Masuk
        tblMasuk.getColumnModel().getColumn(2).setCellRenderer(center);

        // Jenis
        tblMasuk.getColumnModel().getColumn(3).setCellRenderer(center);

        // Total
        tblMasuk.getColumnModel().getColumn(4).setCellRenderer(center);

        // Status
        tblMasuk.getColumnModel().getColumn(5).setCellRenderer(center);
        
        //Menampilkan data laundry masuk
        tampilData("", null);

    }
    //Method untuk menampilkan data laundry masuk ke tabel

    public void tampilData(String keyword,
            java.util.Date tanggal) {

        //Mengambil model tabel
        DefaultTableModel model
                = (DefaultTableModel) tblMasuk.getModel();

        //Menghapus seluruh isi tabel
        model.setRowCount(0);

        //Mengambil data laundry masuk
        List<Transaksi> list
                = controller.getLaundryMasuk(keyword, tanggal);

        //Menampilkan data ke tabel
        for (Transaksi t : list) {

            //Menyimpan teks jenis layanan
            String jenis = t.getJenis();

//Jika jumlah item lebih dari satu
            if (t.getJumlahItem() > 1) {

                //Menambahkan jumlah item lainnya
                jenis = jenis + " +" + (t.getJumlahItem() - 1);

            }

                //Menambahkan data ke tabel
                model.addRow(new Object[]{
                    t.getNoNota(),
                    t.getNamaPelanggan(),
                    FormatJam.format(t.getJamMasuk()),
                    jenis,
                    FormatRupiah.format(t.getTotalHarga()),
                    t.getStatus()
                });
        }

    }
//Method untuk memperbarui data tabel

    public void refreshData() {

        //Menampilkan ulang seluruh data transaksi
        tampilData("", null);

    }
//Method untuk mengambil JTable Laundry Masuk

    public javax.swing.JTable getTblMasuk() {

        //Mengembalikan tabel Laundry Masuk
        return tblMasuk;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMasuk = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1006, 480));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(240, 243, 247));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMinimumSize(new java.awt.Dimension(1006, 75));

        jPanel20.setBackground(new java.awt.Color(232, 240, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 220, 255), 2));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Frame (17).png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(195, 220, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Menampilkan Data Laundry 'Baru Masuk' & baru diproses.");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        jPanel17.setLayout(new java.awt.CardLayout());

        tblMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Nota", "Nama Pelanggan", "Jam Masuk", "Jenis", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMasuk.setGridColor(new java.awt.Color(240, 243, 247));
        tblMasuk.setRowHeight(35);
        tblMasuk.setSelectionBackground(new java.awt.Color(195, 220, 255));
        tblMasuk.setShowGrid(true);
        jScrollPane1.setViewportView(tblMasuk);

        jPanel17.add(jScrollPane1, "card2");

        jPanel2.add(jPanel17, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMasuk;
    // End of variables declaration//GEN-END:variables
}
