package aplikasilaundry.view.panel;

//Mengimpor Frame
import java.awt.Frame;

//Mengimpor SwingUtilities
import javax.swing.SwingUtilities;

//Mengimpor popup tambah item laundry
import aplikasilaundry.view.dialog.popUpTambahItemLaundry;
//Mengimpor model item laundry
import aplikasilaundry.model.ItemLaundry;

import aplikasilaundry.view.panel.TambahLaundry;

import javax.swing.JPanel;

//Mengimpor controller transaksi
import aplikasilaundry.controller.TransaksiController;

//Mengimpor model pelanggan
import aplikasilaundry.model.Pelanggan;
import aplikasilaundry.util.FormatRupiah;
import aplikasilaundry.util.TableStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class PanelItemLaundry extends javax.swing.JPanel {

    //Menyimpan controller transaksi
    private TransaksiController controller;
    private TambahLaundry induk;

    public PanelItemLaundry(TambahLaundry induk) {
        this.induk = induk;

        initComponents();

        //Mengambil controller dari panel induk
        controller = induk.getController();
        //Menampilkan data pelanggan yang sudah dipilih
        tampilDataPelanggan();
        TableStyle.TableStyle(tblItem);
        
        // Lebar kolom tabel
        tblItem.getColumnModel().getColumn(0).setPreferredWidth(50);   // No
        tblItem.getColumnModel().getColumn(1).setPreferredWidth(180);  // Jenis Laundry
        tblItem.getColumnModel().getColumn(2).setPreferredWidth(180);  // Proses
        tblItem.getColumnModel().getColumn(3).setPreferredWidth(100);  // Kg / Biji
        tblItem.getColumnModel().getColumn(4).setPreferredWidth(120);  // Harga
        tblItem.getColumnModel().getColumn(5).setPreferredWidth(120);  // Subtotal

        // ================= Alignment Tabel Item Laundry =================
        // Renderer rata tengah
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        // Renderer rata kiri
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        left.setHorizontalAlignment(SwingConstants.LEFT);

        // No
        tblItem.getColumnModel().getColumn(0).setCellRenderer(center);

        // Jenis Laundry
        tblItem.getColumnModel().getColumn(1).setCellRenderer(left);

        // Proses
        tblItem.getColumnModel().getColumn(2).setCellRenderer(center);

        // Kg / Biji
        tblItem.getColumnModel().getColumn(3).setCellRenderer(center);

        // Harga
        tblItem.getColumnModel().getColumn(4).setCellRenderer(center);

        // Subtotal
        tblItem.getColumnModel().getColumn(5).setCellRenderer(center);

        //Menyiapkan tabel item laundry
        aturTabel();
    }
    //Method untuk menampilkan data pelanggan sementara

    private void tampilDataPelanggan() {

        //Mengambil data pelanggan yang telah dipilih
        Pelanggan pelanggan = controller.getPelangganSementara();

        //Jika belum ada pelanggan, hentikan proses
        if (pelanggan == null) {
            return;
        }

    }
//Method mengatur header tabel item laundry

    private void aturTabel() {

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.addColumn("No.");
        model.addColumn("Jenis Laundry");
        model.addColumn("Proses");
        model.addColumn("Kg / Biji");
        model.addColumn("Harga");
        model.addColumn("Subtotal");

        tblItem.setModel(model);

        }
    //Method untuk menambahkan item laundry ke tabel

    //Method untuk menambahkan item laundry ke tabel
    public void tambahItemKeTabel(ItemLaundry item) {

        //Mengambil model tabel
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblItem.getModel();

        //Nomor urut
        int no = model.getRowCount() + 1;

        String qty;

        if ("Kg".equalsIgnoreCase(item.getSatuan())) {

            if (item.getQty() == (int) item.getQty()) {
                qty = (int) item.getQty() + " Kg";
            } else {
                qty = item.getQty() + " Kg";
            }

        } else {

            qty = (int) item.getQty() + " Biji";

        }

        //Menambahkan data ke tabel
        model.addRow(new Object[]{
            no,
            item.getLayanan(),
            item.getProses(),
            qty,
            FormatRupiah.format(item.getHarga()),
            FormatRupiah.format(item.getSubtotal())
        });

    }
    //Method mengambil controller transaksi

    public TransaksiController getController() {

        //Mengembalikan controller
        return controller;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLanjutKonfirmasi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        pnlTambahItem = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(240, 243, 247));
        jPanel15.setMinimumSize(new java.awt.Dimension(1006, 120));
        jPanel15.setPreferredSize(new java.awt.Dimension(1006, 120));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 243, 247));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));

        btnLanjutKonfirmasi.setBackground(new java.awt.Color(37, 99, 235));
        btnLanjutKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLanjutKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btnLanjutKonfirmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/MaterialSymbolsArrowRightAlt.png"))); // NOI18N
        btnLanjutKonfirmasi.setText("Lanjut ke Konfirmasi");
        btnLanjutKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLanjutKonfirmasi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLanjutKonfirmasi.addActionListener(this::btnLanjutKonfirmasiActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLanjutKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnLanjutKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(240, 243, 247));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 120));

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Kiri.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 243, 247), 10));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel27.setMinimumSize(new java.awt.Dimension(986, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Daftar Item Laundry");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 789, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel26.add(jPanel27, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(966, 75));
        jPanel5.setPreferredSize(new java.awt.Dimension(966, 75));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 75));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 75));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);

        pnlTambahItem.setBackground(new java.awt.Color(240, 243, 247));
        pnlTambahItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTambahItem.setMaximumSize(new java.awt.Dimension(307, 74));
        pnlTambahItem.setMinimumSize(new java.awt.Dimension(307, 74));
        pnlTambahItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTambahItemMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/1.png"))); // NOI18N
        jLabel28.setText("Tambah Item Laundry");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(113, 112, 112));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Tambah item laundry yang dipesan");

        javax.swing.GroupLayout pnlTambahItemLayout = new javax.swing.GroupLayout(pnlTambahItem);
        pnlTambahItem.setLayout(pnlTambahItemLayout);
        pnlTambahItemLayout.setHorizontalGroup(
            pnlTambahItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTambahItemLayout.setVerticalGroup(
            pnlTambahItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTambahItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel8.add(pnlTambahItem);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setMinimumSize(new java.awt.Dimension(966, 25));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.setLayout(new java.awt.CardLayout());

        tblItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Jenis Laundry", "Proses", "Kg / Biji", "Harga", "Subtotal"
            }
        ));
        tblItem.setRowHeight(30);
        tblItem.setShowGrid(true);
        scroll.setViewportView(tblItem);

        jPanel4.add(scroll, "card2");

        jPanel26.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel26, java.awt.BorderLayout.CENTER);

        add(jPanel14, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel9MouseClicked

    private void pnlTambahItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTambahItemMouseClicked
        // TODO add your handling code here:

        //Mengambil frame utama yang sedang aktif
        Frame frame = (Frame) SwingUtilities.getWindowAncestor(this);

        //Membuat popup tambah item laundry
        popUpTambahItemLaundry dialog
                = new popUpTambahItemLaundry(frame, true, PanelItemLaundry.this);

        //Menampilkan popup di tengah panel
        dialog.setLocationRelativeTo(this);

        //Menampilkan popup
        dialog.setVisible(true);


    }//GEN-LAST:event_pnlTambahItemMouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel11MouseClicked

    private void btnLanjutKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutKonfirmasiActionPerformed
        // TODO add your handling code here:
        //Jika belum ada item
        if (tblItem.getRowCount() == 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Tambahkan minimal satu item laundry!");

            return;
        }

//Mengambil panel konfirmasi
        Konfirmasi konfirmasi = induk.getPanelKonfirmasi();

//Menampilkan data pelanggan
        konfirmasi.tampilDataPelanggan(
                controller.getPelangganSementara());

//Menampilkan daftar item
        konfirmasi.tampilItem(
                controller.getDaftarItem());

//Menghitung ringkasan transaksi
        konfirmasi.hitungRingkasan(
                controller.getDaftarItem());

//Menampilkan pesan berhasil
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Item laundry berhasil disimpan.");

//Berpindah ke halaman konfirmasi
        induk.panggilTahap("kartuKonfirmasi");

    }//GEN-LAST:event_btnLanjutKonfirmasiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        //Kembali ke panel pelanggan
        induk.panggilTahap("kartuPelanggan");
    }//GEN-LAST:event_btnKembaliActionPerformed
//Method untuk mereset tabel item laundry

    public void resetForm() {

        //Mengambil model tabel
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblItem.getModel();

        //Menghapus seluruh isi tabel
        model.setRowCount(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjutKonfirmasi;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnlTambahItem;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
