package aplikasilaundry.view.panel;



//Mengimpor SwingUtilities
import javax.swing.SwingUtilities;

//Mengimpor popup tambah item laundry
import aplikasilaundry.view.dialog.popUpTambahItemLaundry;
//Mengimpor model item laundry
import aplikasilaundry.model.ItemLaundry;


//Mengimpor controller transaksi
import aplikasilaundry.controller.TransaksiController;

//Mengimpor model pelanggan
import aplikasilaundry.model.Pelanggan;
import aplikasilaundry.util.FormatRupiah;
import aplikasilaundry.util.TableStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

import aplikasilaundry.view.frame.FrameDashboard;



public class PanelItemLaundry extends javax.swing.JPanel {

    //Menyimpan controller transaksi
    private TransaksiController controller;
    private TambahLaundry induk;

    public PanelItemLaundry(TambahLaundry induk) {
        this.induk = induk;

        initComponents();

        //Mengambil controller dari panel induk
        controller = induk.getController();
        //Menampilkan data pelanggan yang sudah dipilih
        tampilDataPelanggan();
        TableStyle.TableStyle(tblItem);

        // Lebar kolom tabel
        tblItem.getColumnModel().getColumn(0).setPreferredWidth(50);   // No
        tblItem.getColumnModel().getColumn(1).setPreferredWidth(180);  // Jenis Laundry
        tblItem.getColumnModel().getColumn(2).setPreferredWidth(180);  // Proses
        tblItem.getColumnModel().getColumn(3).setPreferredWidth(100);  // Kg / Biji
        tblItem.getColumnModel().getColumn(4).setPreferredWidth(120);  // Harga
        tblItem.getColumnModel().getColumn(5).setPreferredWidth(120);  // Subtotal

        // ================= Alignment Tabel Item Laundry =================
        // Renderer rata tengah
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        // Renderer rata kiri
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        left.setHorizontalAlignment(SwingConstants.LEFT);

        // No
        tblItem.getColumnModel().getColumn(0).setCellRenderer(center);

        // Jenis Laundry
        tblItem.getColumnModel().getColumn(1).setCellRenderer(left);

        // Proses
        tblItem.getColumnModel().getColumn(2).setCellRenderer(center);

        // Kg / Biji
        tblItem.getColumnModel().getColumn(3).setCellRenderer(center);

        // Harga
        tblItem.getColumnModel().getColumn(4).setCellRenderer(center);

        // Subtotal
        tblItem.getColumnModel().getColumn(5).setCellRenderer(center);

        //Menyiapkan tabel item laundry
        aturTabel();
    }
    //Method untuk menampilkan data pelanggan sementara

    private void tampilDataPelanggan() {

        //Mengambil data pelanggan yang telah dipilih
        Pelanggan pelanggan = controller.getPelangganSementara();

        //Jika belum ada pelanggan, hentikan proses
        if (pelanggan == null) {
            return;
        }

    }
//Method mengatur header tabel item laundry

    private void aturTabel() {

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.addColumn("No.");
        model.addColumn("Jenis Laundry");
        model.addColumn("Proses");
        model.addColumn("Kg / Biji");
        model.addColumn("Harga");
        model.addColumn("Subtotal");

        tblItem.setModel(model);

    }
    //Method untuk menambahkan item laundry ke tabel

    //Method untuk menambahkan item laundry ke tabel
    public void tambahItemKeTabel(ItemLaundry item) {

        //Mengambil model tabel
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblItem.getModel();

        //Nomor urut
        int no = model.getRowCount() + 1;

        String qty;

        if ("Kg".equalsIgnoreCase(item.getSatuan())) {

            if (item.getQty() == (int) item.getQty()) {
                qty = (int) item.getQty() + " Kg";
            } else {
                qty = item.getQty() + " Kg";
            }

        } else {

            qty = (int) item.getQty() + " Biji";

        }

        //Menambahkan data ke tabel
        model.addRow(new Object[]{
            no,
            item.getLayanan(),
            item.getProses(),
            qty,
            FormatRupiah.format(item.getHarga()),
            FormatRupiah.format(item.getSubtotal())
        });

    }
    //Method mengambil controller transaksi

    public TransaksiController getController() {

        //Mengembalikan controller
        return controller;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLanjutKonfirmasi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(240, 243, 247));
        jPanel15.setMinimumSize(new java.awt.Dimension(1006, 120));
        jPanel15.setPreferredSize(new java.awt.Dimension(1006, 120));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 243, 247));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));

        btnLanjutKonfirmasi.setBackground(new java.awt.Color(37, 99, 235));
        btnLanjutKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLanjutKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btnLanjutKonfirmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/MaterialSymbolsArrowRightAlt.png"))); // NOI18N
        btnLanjutKonfirmasi.setText("Lanjut ke Konfirmasi");
        btnLanjutKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLanjutKonfirmasi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLanjutKonfirmasi.addActionListener(this::btnLanjutKonfirmasiActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLanjutKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(btnLanjutKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel15.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(240, 243, 247));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 120));

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Kiri.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 243, 247), 10));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel27.setMinimumSize(new java.awt.Dimension(986, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Daftar Item Laundry");

        jButton1.setBackground(new java.awt.Color(37, 99, 235));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/icons8-add-new-20.png"))); // NOI18N
        jButton1.setText("Tambah Item");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 27));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 27));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 617, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        jPanel26.add(jPanel27, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.setLayout(new java.awt.CardLayout());

        tblItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Jenis Laundry", "Proses", "Kg / Biji", "Harga", "Subtotal"
            }
        ));
        tblItem.setRowHeight(30);
        tblItem.setShowGrid(true);
        scroll.setViewportView(tblItem);

        jPanel4.add(scroll, "card2");

        jPanel26.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel26, java.awt.BorderLayout.CENTER);

        add(jPanel14, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutKonfirmasiActionPerformed
        // TODO add your handling code here:
        //Jika belum ada item
        if (tblItem.getRowCount() == 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Tambahkan minimal satu item laundry!");

            return;
        }

//Mengambil panel konfirmasi
        Konfirmasi konfirmasi = induk.getPanelKonfirmasi();

//Menampilkan data pelanggan
        konfirmasi.tampilDataPelanggan(
                controller.getPelangganSementara());

//Menampilkan daftar item
        konfirmasi.tampilItem(
                controller.getDaftarItem());

//Menghitung ringkasan transaksi
        konfirmasi.hitungRingkasan(
                controller.getDaftarItem());

//Menampilkan pesan berhasil
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Item laundry berhasil disimpan.");

//Berpindah ke halaman konfirmasi
        induk.panggilTahap("kartuKonfirmasi");

    }//GEN-LAST:event_btnLanjutKonfirmasiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        //Kembali ke panel pelanggan
        induk.panggilTahap("kartuPelanggan");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          // Mengambil FrameDashboard sebagai parent popup
    FrameDashboard frame =
            (FrameDashboard) SwingUtilities.getWindowAncestor(this);

    // Menampilkan overlay sebelum popup dibuka
    frame.getOverlay().tampilkan();
        //Membuat popup tambah item laundry
        popUpTambahItemLaundry dialog
                = new popUpTambahItemLaundry(frame, true, PanelItemLaundry.this);

        //Menampilkan popup di tengah panel
        dialog.setLocationRelativeTo(this);

        //Menampilkan popup
        dialog.setVisible(true);
        
        // Menyembunyikan overlay setelah popup ditutup
    frame.getOverlay().sembunyikan();

    }//GEN-LAST:event_jButton1ActionPerformed
//Method untuk mereset tabel item laundry

    public void resetForm() {

        //Mengambil model tabel
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblItem.getModel();

        //Menghapus seluruh isi tabel
        model.setRowCount(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjutKonfirmasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
