package aplikasilaundry.view.panel;
//Mengimpor controller transaksi

import aplikasilaundry.controller.TransaksiController;

//Mengimpor model transaksi
import aplikasilaundry.model.Transaksi;
import aplikasilaundry.util.FormatJam;
import aplikasilaundry.util.FormatRupiah;
import aplikasilaundry.util.TableStyle;

//Mengimpor DefaultTableModel
import javax.swing.table.DefaultTableModel;

//Mengimpor collection
import java.util.List;

//Panel untuk menampilkan seluruh data laundry
public class Semua extends javax.swing.JPanel {

    //Menyimpan controller transaksi
    private TransaksiController controller;

    public Semua() {
        initComponents();

        //Membuat objek controller
        controller = new TransaksiController();
        TableStyle.TableStyle(tblSemua);

        //Menampilkan data ke tabel
       tampilData("", null);
        tblSemua.getColumnModel()
                .getColumn(5);
    }

    //Method untuk menampilkan data transaksi ke tabel
   public void tampilData(String keyword,
                       java.util.Date tanggal) {

        //Mengambil model tabel
        DefaultTableModel model = (DefaultTableModel) tblSemua.getModel();

        //Menghapus seluruh isi tabel
        model.setRowCount(0);

        //Mengambil seluruh data transaksi
        List<Transaksi> list =
        controller.getAll(keyword, tanggal);

        //Menampilkan jumlah data yang diterima
        System.out.println("Data diterima = " + list.size());

        //Menampilkan data satu per satu
        for (Transaksi t : list) {

            //Menyimpan teks jenis layanan
            String jenis = t.getJenis();

//Jika jumlah item lebih dari satu
            if (t.getJumlahItem() > 1) {

                //Menambahkan jumlah item lain
                jenis = jenis + " +" + (t.getJumlahItem() - 1);

            }

//Menambahkan data ke tabel
            model.addRow(new Object[]{
                //Nomor nota
                t.getNoNota(),
                //Nama pelanggan
                t.getNamaPelanggan(),
                //Jam masuk
                FormatJam.format(
                t.getJamMasuk()),
                //Jenis layanan
                jenis,
                //Total harga
                FormatRupiah.format(
                t.getTotalHarga()),
                //Status transaksi
                t.getStatus()

            });
        }
    }

//Method untuk memperbarui data tabel
    public void refreshData() {

        //Menampilkan ulang seluruh data transaksi
        tampilData("", null);

    }
//Method untuk mengambil JTable Laundry Masuk

    public javax.swing.JTable getTblMasuk() {

        //Mengembalikan tabel Laundry Masuk
        return tblSemua;

    }
//Method untuk mengambil JTable

    public javax.swing.JTable getTblSemua() {
        return tblSemua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSemua = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(240, 243, 247));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setMinimumSize(new java.awt.Dimension(1006, 75));

        jPanel22.setBackground(new java.awt.Color(232, 240, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 220, 255), 2));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Frame (17).png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(195, 220, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Menampilkan Data Laundry 'Baru Masuk' & baru diproses.");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jPanel17.setLayout(new java.awt.CardLayout());

        tblSemua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Nota", "Nama Pelanggan", "Jam Masuk", "Jenis", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSemua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSemua.setRowHeight(35);
        tblSemua.setShowGrid(true);
        jScrollPane1.setViewportView(tblSemua);

        jPanel17.add(jScrollPane1, "card2");

        jPanel4.add(jPanel17, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSemua;
    // End of variables declaration//GEN-END:variables
}
