
package aplikasilaundry.view.panel;

import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
//Mengimpor controller transaksi
import aplikasilaundry.controller.TransaksiController;

public class TambahLaundry extends javax.swing.JPanel {

    //Controller transaksi yang dipakai semua panel
private TransaksiController controller = new TransaksiController();

//Panel pelanggan
private PanelPelanggan panelPelanggan;

//Panel item
private PanelItemLaundry panelItem;

//Panel konfirmasi
private Konfirmasi panelKonfirmasi;



    public TambahLaundry() {
        initComponents();
        //Membuat panel pelanggan
panelPelanggan = new PanelPelanggan(this);

//Membuat panel item
panelItem = new PanelItemLaundry(this);

//Membuat panel konfirmasi
panelKonfirmasi = new Konfirmasi(this);

//Menambahkan panel ke CardLayout
panelContentPelanggan.add(panelPelanggan,"kartuPelanggan");
panelContentPelanggan.add(panelItem,"kartuItem");
panelContentPelanggan.add(panelKonfirmasi,"kartuKonfirmasi");
        //Menampilkan tahap pertama saat panel dibuka
    panggilTahap("kartuPelanggan");
    }
    //Method untuk mereset seluruh form Tambah Laundry
public void resetForm(){

    //Mereset panel pelanggan
    panelPelanggan.resetForm();

    //Mereset panel item laundry
    panelItem.resetForm();

    //Mereset panel konfirmasi
    panelKonfirmasi.resetForm();

    //Menampilkan kembali panel pelanggan
    panggilTahap("kartuPelanggan");

}
    //Method mengambil controller transaksi
public TransaksiController getController() {

    //Mengembalikan controller
    return controller;

}

//Method mengambil panel konfirmasi
public Konfirmasi getPanelKonfirmasi() {

    //Mengembalikan panel konfirmasi
    return panelKonfirmasi;

}

    public void panggilTahap(String namaKartu) {
        // 1. Ambil Layout CardLayout dari jPanel26 (sesuai nama panel CardLayout Anda di gambar Navigator)
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContentPelanggan.getLayout();
        cl.show(panelContentPelanggan, namaKartu);

        // 2. Logika mengubah warna teks/indikator navigasi di bagian atas agar interaktif
        lblPelanggan.setBackground(Color.WHITE);
        lblItem.setBackground(Color.WHITE);
        lblKonfirmasi.setBackground(Color.WHITE);

        // Ubah warna label sesuai panel yang aktif
        if (namaKartu.equals("kartuPelanggan")) {

            // Icon
            jLabel71.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/1 warna.png")));
            jLabel75.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/2 no warna.png")));
            jLabel39.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/3.png")));

            // Label
            ubahWarnaLabel(lblPelanggan, new Color(0, 102, 204));
            ubahWarnaLabel(lblItem, Color.BLACK);
            ubahWarnaLabel(lblKonfirmasi, Color.BLACK);

        } else if (namaKartu.equals("kartuItem")) {

            // Icon
            jLabel71.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/1 no warna.png")));
            jLabel75.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/2.png")));
            jLabel39.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/3.png")));

            // Label
            ubahWarnaLabel(lblPelanggan, Color.BLACK);
            ubahWarnaLabel(lblItem, new Color(0, 102, 204));
            ubahWarnaLabel(lblKonfirmasi, Color.BLACK);

        } else if (namaKartu.equals("kartuKonfirmasi")) {

            // Icon
            jLabel71.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/1 no warna.png")));
            jLabel75.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/2 no warna.png")));
            jLabel39.setIcon(new ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/3 warna.png")));

            // Label
            ubahWarnaLabel(lblPelanggan, Color.BLACK);
            ubahWarnaLabel(lblItem, Color.BLACK);
            ubahWarnaLabel(lblKonfirmasi, new Color(0, 102, 204));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel20 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblPelanggan = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        lblItem = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        lblKonfirmasi = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        panelContentPelanggan = new javax.swing.JPanel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 243, 247), 10));
        setMinimumSize(new java.awt.Dimension(1006, 728));
        setPreferredSize(new java.awt.Dimension(1006, 728));
        setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(1006, 215));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(240, 243, 247));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 243, 247), 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Laundry - Transaksi Baru");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(113, 112, 112));
        jLabel3.setText("Lengkapi data di bawah ini untuk membuat transaksi baru");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel18.setBackground(new java.awt.Color(240, 243, 247));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 243, 247), 10));
        jPanel18.setMinimumSize(new java.awt.Dimension(797, 115));

        lblPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        lblPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPelangganMouseClicked(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel70.setText("Data Pelanggan");

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/1 no warna.png"))); // NOI18N

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(113, 112, 112));
        jLabel72.setText("Masukkan data pelanggan");

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/MaterialSymbolsChevronRight (1).png"))); // NOI18N

        javax.swing.GroupLayout lblPelangganLayout = new javax.swing.GroupLayout(lblPelanggan);
        lblPelanggan.setLayout(lblPelangganLayout);
        lblPelangganLayout.setHorizontalGroup(
            lblPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblPelangganLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel73)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        lblPelangganLayout.setVerticalGroup(
            lblPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblPelangganLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(lblPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(lblPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel72))
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblItem.setBackground(new java.awt.Color(255, 255, 255));
        lblItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemMouseClicked(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel74.setText("Item Loundry");

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/2 no warna.png"))); // NOI18N

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(113, 112, 112));
        jLabel76.setText("Tambah item loundry");

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/MaterialSymbolsChevronRight (1).png"))); // NOI18N

        javax.swing.GroupLayout lblItemLayout = new javax.swing.GroupLayout(lblItem);
        lblItem.setLayout(lblItemLayout);
        lblItemLayout.setHorizontalGroup(
            lblItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblItemLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel77)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        lblItemLayout.setVerticalGroup(
            lblItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblItemLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(lblItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(lblItemLayout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel76))
                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        lblKonfirmasi.setBackground(new java.awt.Color(255, 255, 255));
        lblKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKonfirmasiMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        jLabel38.setText("Konfirmasi");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/3.png"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(113, 112, 112));
        jLabel40.setText("Periksa dan konfirmasi data");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/MaterialSymbolsChevronRight (1).png"))); // NOI18N

        javax.swing.GroupLayout lblKonfirmasiLayout = new javax.swing.GroupLayout(lblKonfirmasi);
        lblKonfirmasi.setLayout(lblKonfirmasiLayout);
        lblKonfirmasiLayout.setHorizontalGroup(
            lblKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(17, 17, 17))
        );
        lblKonfirmasiLayout.setVerticalGroup(
            lblKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblKonfirmasiLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(lblKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(lblKonfirmasiLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40))
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(lblPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel13.add(jPanel18, java.awt.BorderLayout.CENTER);

        add(jPanel13, java.awt.BorderLayout.PAGE_START);

        panelContentPelanggan.setBackground(new java.awt.Color(240, 243, 247));
        panelContentPelanggan.setLayout(new java.awt.CardLayout());
        add(panelContentPelanggan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel27MouseClicked

    private void lblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPelangganMouseClicked
        // TODO add your handling code here:
        panggilTahap("kartuPelanggan");
    }//GEN-LAST:event_lblPelangganMouseClicked

    private void lblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseClicked
        // TODO add your handling code here:
        panggilTahap("kartuItem");
    }//GEN-LAST:event_lblItemMouseClicked

    private void lblKonfirmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKonfirmasiMouseClicked
        // TODO add your handling code here:
        panggilTahap("kartuKonfirmasi");
    }//GEN-LAST:event_lblKonfirmasiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel lblItem;
    private javax.swing.JPanel lblKonfirmasi;
    private javax.swing.JPanel lblPelanggan;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panelContentPelanggan;
    // End of variables declaration//GEN-END:variables

    private void ubahWarnaLabel(JPanel panel, Color warna) {

        for (Component c : panel.getComponents()) {

            if (c instanceof JLabel) {
                ((JLabel) c).setForeground(warna);
            }

        }
    }
}
