/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasilaundry.view;

import aplikasilaundry.view.layout.main.Dasboard;
import aplikasilaundry.view.layout.main.DataLaundry.LaundryMasuk;
import aplikasilaundry.view.layout.main.DataLaundry.SelesaiBelumDiambil;
import aplikasilaundry.view.layout.main.DataLaundry.Semua;
import aplikasilaundry.view.layout.main.LaporanPemasukan;
import aplikasilaundry.view.layout.main.Pengaturannewpackage.Pengaturan;
import aplikasilaundry.view.layout.main.RiwayatLaundry;
import aplikasilaundry.view.layout.main.TambahLaoundry.PanelKonfirmasi.Konfirmasi;
import aplikasilaundry.view.layout.main.TambahLaundry.TambahLaundry;
import aplikasilaundry.view.layout.main.TambahLaoundry.itemLaundrynewpackage.ItemLoundry;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sirdzat
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        inisiasiPanel();
    }
    
    void inisiasiPanel(){
        cardLayout = (CardLayout)panelContent.getLayout();
        panelContent.add(new Dasboard(), "dashboard");
        panelContent.add(new LaundryMasuk(), "laundryMasuk");
        panelContent.add(new LaporanPemasukan(), "laporanPemasukan");
        panelContent.add(new SelesaiBelumDiambil(), "selesaiBelumDiambil");
        panelContent.add(new Semua(), "semua");
        panelContent.add(new Pengaturan(), "pengaturan");
        panelContent.add(new TambahLaundry(), "tambahLaundry");
        panelContent.add(new Konfirmasi(), "konfirmasi");
        panelContent.add(new ItemLoundry(), "itemLaundry");
        panelContent.add(new RiwayatLaundry(), "riwayat");
        
        cardLayout.show(panelContent, "dashboard");

    panelContent.revalidate();
    panelContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDasboard = new javax.swing.JButton();
        btnDataLaundry = new javax.swing.JButton();
        btnRiwayatLaundry = new javax.swing.JButton();
        btnTambahLaundry = new javax.swing.JButton();
        btnLaporanPemasukan = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(37, 99, 235));
        panelSidebar.setPreferredSize(new java.awt.Dimension(274, 728));

        jLabel1.setBackground(new java.awt.Color(37, 99, 235));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/img/logo.png"))); // NOI18N

        btnDasboard.setBackground(new java.awt.Color(37, 99, 235));
        btnDasboard.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnDasboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Frame11.png"))); // NOI18N
        btnDasboard.setText("Dasboard");
        btnDasboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnDasboard.setBorderPainted(false);
        btnDasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDasboard.setIconTextGap(15);
        btnDasboard.setPreferredSize(new java.awt.Dimension(238, 45));
        btnDasboard.addActionListener(this::btnDasboardActionPerformed);

        btnDataLaundry.setBackground(new java.awt.Color(37, 99, 235));
        btnDataLaundry.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnDataLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnDataLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/ArcticonsSimplenotes 1.png"))); // NOI18N
        btnDataLaundry.setText("Data Laundry");
        btnDataLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnDataLaundry.setBorderPainted(false);
        btnDataLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataLaundry.setIconTextGap(11);
        btnDataLaundry.setPreferredSize(new java.awt.Dimension(238, 45));
        btnDataLaundry.addActionListener(this::btnDataLaundryActionPerformed);

        btnRiwayatLaundry.setBackground(new java.awt.Color(37, 99, 235));
        btnRiwayatLaundry.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnRiwayatLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayatLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/TeenyiconsTickCircleOutline 1.png"))); // NOI18N
        btnRiwayatLaundry.setText("Riwayat Laundry");
        btnRiwayatLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 22, 1, 1));
        btnRiwayatLaundry.setBorderPainted(false);
        btnRiwayatLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRiwayatLaundry.setIconTextGap(15);
        btnRiwayatLaundry.setPreferredSize(new java.awt.Dimension(238, 45));
        btnRiwayatLaundry.addActionListener(this::btnRiwayatLaundryActionPerformed);

        btnTambahLaundry.setBackground(new java.awt.Color(37, 99, 235));
        btnTambahLaundry.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnTambahLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Vector (3).png"))); // NOI18N
        btnTambahLaundry.setText("Tambah Laundry");
        btnTambahLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 22, 1, 1));
        btnTambahLaundry.setBorderPainted(false);
        btnTambahLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambahLaundry.setIconTextGap(17);
        btnTambahLaundry.setPreferredSize(new java.awt.Dimension(238, 45));
        btnTambahLaundry.addActionListener(this::btnTambahLaundryActionPerformed);

        btnLaporanPemasukan.setBackground(new java.awt.Color(37, 99, 235));
        btnLaporanPemasukan.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnLaporanPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanPemasukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/IconoirReports 1.png"))); // NOI18N
        btnLaporanPemasukan.setText("Laporan Pemasukan");
        btnLaporanPemasukan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnLaporanPemasukan.setBorderPainted(false);
        btnLaporanPemasukan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporanPemasukan.setIconTextGap(15);
        btnLaporanPemasukan.setPreferredSize(new java.awt.Dimension(238, 45));
        btnLaporanPemasukan.addActionListener(this::btnLaporanPemasukanActionPerformed);

        btnPengaturan.setBackground(new java.awt.Color(37, 99, 235));
        btnPengaturan.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/icon pengaturan.png"))); // NOI18N
        btnPengaturan.setText("Pengaturan");
        btnPengaturan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnPengaturan.setBorderPainted(false);
        btnPengaturan.setDefaultCapable(false);
        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengaturan.setIconTextGap(10);
        btnPengaturan.setPreferredSize(new java.awt.Dimension(238, 45));
        btnPengaturan.addActionListener(this::btnPengaturanActionPerformed);

        btnLogout.setBackground(new java.awt.Color(37, 99, 235));
        btnLogout.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Frame (10).png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(15);
        btnLogout.setPreferredSize(new java.awt.Dimension(238, 45));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTambahLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDasboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDataLaundry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRiwayatLaundry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLaporanPemasukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPengaturan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDasboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDataLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRiwayatLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporanPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dashboard");
    }//GEN-LAST:event_btnDasboardActionPerformed

    private void btnDataLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataLaundryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "semua");
    }//GEN-LAST:event_btnDataLaundryActionPerformed

    private void btnRiwayatLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatLaundryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "riwayat");
    }//GEN-LAST:event_btnRiwayatLaundryActionPerformed

    private void btnTambahLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLaundryActionPerformed
        // TODO add your handling code here:
         cardLayout.show(panelContent, "tambahLaundry");
    }//GEN-LAST:event_btnTambahLaundryActionPerformed

    private void btnLaporanPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPemasukanActionPerformed
        // TODO add your handling code here:
         cardLayout.show(panelContent, "laporanPemasukan");
    }//GEN-LAST:event_btnLaporanPemasukanActionPerformed

    private void btnPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaturanActionPerformed
        // TODO add your handling code here:
         cardLayout.show(panelContent, "pengaturan");
    }//GEN-LAST:event_btnPengaturanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
            try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDasboard;
    private javax.swing.JButton btnDataLaundry;
    private javax.swing.JButton btnLaporanPemasukan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.JButton btnRiwayatLaundry;
    private javax.swing.JButton btnTambahLaundry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
