/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasilaundry.view;

import aplikasilaundry.view.layout.main.Dasboard;
import aplikasilaundry.view.layout.main.DataLaundry.Diproses;
import aplikasilaundry.view.layout.main.DataLaundry.LaundryMasuk;
import aplikasilaundry.view.layout.main.DataLaundry.SelesaiBelumDiambil;
import aplikasilaundry.view.layout.main.DataLaundry.DataLaundry;
import aplikasilaundry.view.layout.main.LaporanPemasukan;
import aplikasilaundry.view.layout.main.Pengaturan.Pengaturan;
import aplikasilaundry.view.layout.main.RiwayatLaundry;
import aplikasilaundry.view.layout.main.TambahLaundry.TambahLaundry;
import aplikasilaundry.view.layout.main.popUpLogout;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sirdzat
 */
public class mainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        inisiasiPanel();
        
        btnDasboard.setSelected(true);
        setMenuAktif(btnDasboard);
    }


    void inisiasiPanel() {
        cardLayout = (CardLayout) panelContent.getLayout();
        panelContent.add(new Dasboard(), "dashboard");
        panelContent.add(new LaundryMasuk(), "laundryMasuk");
        panelContent.add(new LaporanPemasukan(), "laporanPemasukan");
        panelContent.add(new SelesaiBelumDiambil(), "selesaiBelumDiambil");
        panelContent.add(new DataLaundry(), "semua");
        panelContent.add(new Diproses(), "diproses");
        panelContent.add(new Pengaturan(), "pengaturan");
        panelContent.add(new TambahLaundry(), "tambahLaundry");
        panelContent.add(new RiwayatLaundry(), "riwayat");
        cardLayout.show(panelContent, "dashboard");

        panelContent.revalidate();
        panelContent.repaint();
    }

    public void panggilHalaman(String namaHalaman) {
        cardLayout.show(panelContent, namaHalaman);

        // Agar JToggleButton di sidebar otomatis ikut menyala sesuai halaman
        // 2. Logika agar JToggleButton di sidebar otomatis menyala sesuai halaman tujuan
        if (namaHalaman.equals("dashboard")) {
            btnDasboard.setSelected(true);
        } else if (namaHalaman.equals("tambahLaundry")) {
            btnTambahLaundry.setSelected(true);
        } else if (namaHalaman.equals("riwayat")) {
            btnRiwayatLaundry.setSelected(true);
        } else if (namaHalaman.equals("laporanPemasukan")) {
            btnLaporanPemasukan.setSelected(true);
        } else if (namaHalaman.equals("pengaturan")) {
            btnPengaturan.setSelected(true);
        } else if (namaHalaman.equals("laundryMasuk") || namaHalaman.equals("diproses")
                    || namaHalaman.equals("selesaiBelumDiambil") || namaHalaman.equals("semua")) {
                // Jika yang dibuka adalah sub-halaman data laundry, maka tombol Data Laundry yang menyala
                btnDataLaundry.setSelected(true);
            }
        }

    private void setMenuAktif(JToggleButton tombol) { 

        if (tombol.isSelected()) {
            tombol.putClientProperty("FlatLaf.style",
                    "background:#FFFFFF;"
                    + "foreground:#2563EB;");
        } else {
            tombol.putClientProperty("FlatLaf.style",
                    "background:#2563EB;"
                    + "foreground:#FFFFFF;");
        }
        tombol.revalidate();
        tombol.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDasboard = new javax.swing.JToggleButton();
        btnTambahLaundry = new javax.swing.JToggleButton();
        btnDataLaundry = new javax.swing.JToggleButton();
        btnRiwayatLaundry = new javax.swing.JToggleButton();
        btnLaporanPemasukan = new javax.swing.JToggleButton();
        btnPengaturan = new javax.swing.JToggleButton();
        btnLogout = new javax.swing.JToggleButton();
        panelContent = new javax.swing.JPanel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(37, 99, 235));
        panelSidebar.setMinimumSize(new java.awt.Dimension(274, 728));
        panelSidebar.setPreferredSize(new java.awt.Dimension(274, 728));

        jLabel1.setBackground(new java.awt.Color(37, 99, 235));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/img/logo.png"))); // NOI18N

        btnDasboard.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnDasboard);
        btnDasboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDasboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Home.png"))); // NOI18N
        btnDasboard.setText("Dasboard");
        btnDasboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnDasboard.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Home.png"))); // NOI18N
        btnDasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDasboard.setIconTextGap(17);
        btnDasboard.setPreferredSize(new java.awt.Dimension(112, 40));
        btnDasboard.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Home.png"))); // NOI18N
        btnDasboard.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Dasboard biru.png"))); // NOI18N
        btnDasboard.addItemListener(this::btnDasboardItemStateChanged);
        btnDasboard.addActionListener(this::btnDasboardActionPerformed);

        btnTambahLaundry.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnTambahLaundry);
        btnTambahLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambahLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Tambah.png"))); // NOI18N
        btnTambahLaundry.setText("Tambah Laundry");
        btnTambahLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnTambahLaundry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambahLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambahLaundry.setIconTextGap(17);
        btnTambahLaundry.setPreferredSize(new java.awt.Dimension(112, 40));
        btnTambahLaundry.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Tambah.png"))); // NOI18N
        btnTambahLaundry.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Tambah Biru.png"))); // NOI18N
        btnTambahLaundry.addItemListener(this::btnTambahLaundryItemStateChanged);
        btnTambahLaundry.addActionListener(this::btnTambahLaundryActionPerformed);

        btnDataLaundry.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnDataLaundry);
        btnDataLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnDataLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/data laundry.png"))); // NOI18N
        btnDataLaundry.setText("Data Laundry");
        btnDataLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnDataLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataLaundry.setIconTextGap(19);
        btnDataLaundry.setPreferredSize(new java.awt.Dimension(112, 40));
        btnDataLaundry.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Data Biru.png"))); // NOI18N
        btnDataLaundry.addItemListener(this::btnDataLaundryItemStateChanged);
        btnDataLaundry.addActionListener(this::btnDataLaundryActionPerformed);

        btnRiwayatLaundry.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnRiwayatLaundry);
        btnRiwayatLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRiwayatLaundry.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayatLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/riwayat laundry.png"))); // NOI18N
        btnRiwayatLaundry.setText("Riwayat Laundry");
        btnRiwayatLaundry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnRiwayatLaundry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRiwayatLaundry.setIconTextGap(15);
        btnRiwayatLaundry.setPreferredSize(new java.awt.Dimension(112, 40));
        btnRiwayatLaundry.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Riwayat Biru.png"))); // NOI18N
        btnRiwayatLaundry.addItemListener(this::btnRiwayatLaundryItemStateChanged);
        btnRiwayatLaundry.addActionListener(this::btnRiwayatLaundryActionPerformed);

        btnLaporanPemasukan.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnLaporanPemasukan);
        btnLaporanPemasukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporanPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanPemasukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/riwayat pemasukan.png"))); // NOI18N
        btnLaporanPemasukan.setText("Laporan Pemasukan");
        btnLaporanPemasukan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnLaporanPemasukan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporanPemasukan.setIconTextGap(15);
        btnLaporanPemasukan.setPreferredSize(new java.awt.Dimension(112, 40));
        btnLaporanPemasukan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Laporan biru.png"))); // NOI18N
        btnLaporanPemasukan.addItemListener(this::btnLaporanPemasukanItemStateChanged);
        btnLaporanPemasukan.addActionListener(this::btnLaporanPemasukanActionPerformed);

        btnPengaturan.setBackground(new java.awt.Color(37, 99, 235));
        buttonGroup1.add(btnPengaturan);
        btnPengaturan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/pengaturan.png"))); // NOI18N
        btnPengaturan.setText("Pengaturan");
        btnPengaturan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengaturan.setIconTextGap(10);
        btnPengaturan.setPreferredSize(new java.awt.Dimension(112, 40));
        btnPengaturan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/Pengaturan Biru.png"))); // NOI18N
        btnPengaturan.addItemListener(this::btnPengaturanItemStateChanged);
        btnPengaturan.addActionListener(this::btnPengaturanActionPerformed);

        btnLogout.setBackground(new java.awt.Color(37, 99, 235));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/asset/icon/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(17);
        btnLogout.setPreferredSize(new java.awt.Dimension(112, 40));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDasboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(btnTambahLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDataLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRiwayatLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporanPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDasboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRiwayatLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporanPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setMinimumSize(new java.awt.Dimension(1006, 728));
        panelContent.setPreferredSize(new java.awt.Dimension(1006, 728));
        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "dashboard");
        
    }//GEN-LAST:event_btnDasboardActionPerformed

    private void btnTambahLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLaundryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "tambahLaundry");
        
    }//GEN-LAST:event_btnTambahLaundryActionPerformed

    private void btnDataLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataLaundryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "semua");
    }//GEN-LAST:event_btnDataLaundryActionPerformed

    private void btnRiwayatLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatLaundryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "riwayat");
    }//GEN-LAST:event_btnRiwayatLaundryActionPerformed

    private void btnLaporanPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanPemasukanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "laporanPemasukan");
    }//GEN-LAST:event_btnLaporanPemasukanActionPerformed

    private void btnPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaturanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "pengaturan");
    }//GEN-LAST:event_btnPengaturanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        popUpLogout dialog = new popUpLogout(this, true);
        // 3. Tampilkan popup
        dialog.setVisible(true);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDasboardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnDasboardItemStateChanged
        // TODO add your handling code here:
        setMenuAktif(btnDasboard);
    }//GEN-LAST:event_btnDasboardItemStateChanged

    private void btnTambahLaundryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTambahLaundryItemStateChanged
        // TODO add your handling code here:
        setMenuAktif(btnTambahLaundry);
    }//GEN-LAST:event_btnTambahLaundryItemStateChanged

    private void btnDataLaundryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnDataLaundryItemStateChanged
        // TODO add your handling code here:
                setMenuAktif(btnDataLaundry);

        
    }//GEN-LAST:event_btnDataLaundryItemStateChanged

    private void btnRiwayatLaundryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnRiwayatLaundryItemStateChanged
        // TODO add your handling code here:
                setMenuAktif(btnRiwayatLaundry);

     
    }//GEN-LAST:event_btnRiwayatLaundryItemStateChanged

    private void btnLaporanPemasukanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnLaporanPemasukanItemStateChanged
        // TODO add your handling code here:
                setMenuAktif(btnLaporanPemasukan);

        
    }//GEN-LAST:event_btnLaporanPemasukanItemStateChanged

    private void btnPengaturanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnPengaturanItemStateChanged
        // TODO add your handling code here:
                setMenuAktif(btnPengaturan);

        
    }//GEN-LAST:event_btnPengaturanItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDasboard;
    private javax.swing.JToggleButton btnDataLaundry;
    private javax.swing.JToggleButton btnLaporanPemasukan;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnPengaturan;
    private javax.swing.JToggleButton btnRiwayatLaundry;
    private javax.swing.JToggleButton btnTambahLaundry;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
